// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5UC3REPvAoX3dkDpWDXpIXk1YqbVZF04',
    appId: '1:495135160328:web:a29ecd1c8b196b98e8b9bd',
    messagingSenderId: '495135160328',
    projectId: 'moveit-e3963',
    authDomain: 'moveit-e3963.firebaseapp.com',
    storageBucket: 'moveit-e3963.firebasestorage.app',
    measurementId: 'G-K7QMGJJCKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABgc7l-hhJB0Wm9ysmqATa3kfjMpIBvtc',
    appId: '1:495135160328:android:b0591e49b73aae46e8b9bd',
    messagingSenderId: '495135160328',
    projectId: 'moveit-e3963',
    storageBucket: 'moveit-e3963.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1SQSXkE2hmxAhZHxxo1Y3w5FGJxz7H-U',
    appId: '1:495135160328:ios:b043038de2464bf0e8b9bd',
    messagingSenderId: '495135160328',
    projectId: 'moveit-e3963',
    storageBucket: 'moveit-e3963.firebasestorage.app',
    iosBundleId: 'com.example.moveit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1SQSXkE2hmxAhZHxxo1Y3w5FGJxz7H-U',
    appId: '1:495135160328:ios:b043038de2464bf0e8b9bd',
    messagingSenderId: '495135160328',
    projectId: 'moveit-e3963',
    storageBucket: 'moveit-e3963.firebasestorage.app',
    iosBundleId: 'com.example.moveit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5UC3REPvAoX3dkDpWDXpIXk1YqbVZF04',
    appId: '1:495135160328:web:5755b27d16d165a3e8b9bd',
    messagingSenderId: '495135160328',
    projectId: 'moveit-e3963',
    authDomain: 'moveit-e3963.firebaseapp.com',
    storageBucket: 'moveit-e3963.firebasestorage.app',
    measurementId: 'G-CR17SZ04CK',
  );
}
